### PR TITLE
allow dotless domains

### PR DESCRIPTION
**Pull request by bjfletcher**
using the HTML5 standard regular expression

### CODE REVIEW

**Comment by keithamus** [comment]
Commit message should probably change, as the w3c regex _doesn't allow_ dotless domains

**Comment by ironsidevsquincy** [comment]
👎 

This is going to confuse the hell out of anyone reading it, for no discernible benefit

**Comment by ironsidevsquincy** [comment]
But willing to go with the majority if people think it's worth it

**Comment by bjfletcher** [comment]
@keithamus I've just reworded the commit

**Comment by bjfletcher** [comment]
it's since turned out that, in fact, W3C says dotless domain is permissible :)

**Pull request merged**
